apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-dev-app
  namespace: mogenius-argo-cd
  labels:
    managed-by: mogenius
spec:
  destination:
    name: in-cluster
    namespace: argo-dev
  syncPolicy:
    automated:
      prune: true
      enabled: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: mogenius
  source:
    repoURL: https://helm.mogenius.com/public
    targetRevision: 1.2.2
    chart: moac
    helm:
      releaseName: argo-dev-app
      valuesObject:
        configmaps: []
        sealedSecrets: []
        controllers: []
        services: []
        ingresses: []
        rawResources:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              annotations: {}
              name: my-deployment
              namespace: argo-dev
            spec:
              progressDeadlineSeconds: 600
              replicas: 1
              revisionHistoryLimit: 10
              selector:
                matchLabels:
                  app: my-deployment
              strategy:
                rollingUpdate:
                  maxSurge: 25%
                  maxUnavailable: 25%
                type: RollingUpdate
              template:
                metadata:
                  labels:
                    app: my-deployment
                spec:
                  containers:
                    - image: nginx:latest
                      imagePullPolicy: Always
                      name: my-container
                      resources: {}
                      terminationMessagePath: /dev/termination-log
                      terminationMessagePolicy: File
                  dnsPolicy: ClusterFirst
                  restartPolicy: Always
                  schedulerName: default-scheduler
                  securityContext: {}
                  terminationGracePeriodSeconds: 30
