apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saddas
  namespace: mogenius-argo-cd
  labels:
    managed-by: mogenius
spec:
  destination:
    name: in-cluster
    namespace: argo
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: mogenius
  source:
    repoURL: https://helm.mogenius.com/public
    targetRevision: 1.2.2
    chart: moac
    helm:
      releaseName: saddas
      valuesObject:
        configmaps: []
        sealedSecrets: []
        controllers: []
        services: []
        ingresses: []
        rawResources: []
