apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-loading
  namespace: mogenius-argo-cd
  labels:
    managed-by: mogenius
spec:
  destination:
    name: in-cluster
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
  project: mogenius
  source:
    repoURL: https://helm.mogenius.com/public
    targetRevision: 1.2.2
    chart: moac
    helm:
      releaseName: test-loading
      valuesObject:
        configmaps: []
        sealedSecrets: []
        controllers: []
        services: []
        ingresses: []
        rawResources:
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata:
              name: my-role-dammm
              namespace: wordpress
            rules:
              - apiGroups:
                  - ''
                resources:
                  - pods
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - events.k8s.io
                resources:
                  - events
                verbs:
                  - '*'
              - apiGroups:
                  - batch
                resources:
                  - cronjobs
                verbs:
                  - '*'
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata:
              name: my-role-date-test
              namespace: wordpress
            rules:
              - apiGroups:
                  - ''
                resources:
                  - pods
                verbs:
                  - get
                  - list
                  - watch
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              annotations:
                pv.kubernetes.io/bind-completed: 'yes'
                pv.kubernetes.io/bound-by-controller: 'yes'
                volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
                volume.kubernetes.io/selected-node: test-server-sami
                volume.kubernetes.io/storage-provisioner: rancher.io/local-path
              finalizers:
                - kubernetes.io/pvc-protection
              labels:
                app.kubernetes.io/component: primary
                app.kubernetes.io/name: mariadb
                app.kubernetes.io/part-of: mariadb
              name: data-wordpress-mariadb-0
              namespace: wordpress
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 8Gi
              storageClassName: local-path
              volumeMode: Filesystem
              volumeName: pvc-1a554728-41d1-4b2d-9823-cc902f2e623d
